package com.cakeit.cakitandroid.presentation.mypage.announcement

import android.app.Application
import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.cakeit.cakitandroid.base.BaseViewModel
import com.cakeit.cakitandroid.domain.model.TextboardModel

class AnnouncementListViewModel(application: Application) : BaseViewModel<Any?>(application)  {

    private val _announcementListItems = MutableLiveData<ArrayList<TextboardModel>>()
    val announcementListItems : LiveData<ArrayList<TextboardModel>> get() = _announcementListItems

    init {

    }

    fun add(){
        val tms = arrayListOf<TextboardModel>()
        tms.add(TextboardModel(1, "test1", "testBody1", "2020.11.14"))
        tms.add(TextboardModel(2, "test2", "testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1testBody1", "2020.11.14"))
        tms.add(TextboardModel(3, "test3test3test3test3test3test3test3test3test3test3test3", "testBody1", "2020.11.14"))
        tms.add(TextboardModel(4, "final", "testBody1", "2020.11.14"))
        _announcementListItems.value = tms
    }
}